[package]
name = "solana-ft"
version = "0.1.0"
description = "Solana Fungible Token"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "solana_ft"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"] # !!!
anchor-debug  = []


[dependencies]
anchor-lang = { version = "0.31.1" }
anchor-spl = "0.31.1"
