[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft = "CjLs3iFDVrtJwXpubVaGmz2hJrVR4F9UAYxma2oxwL2G"
solana_ft = "DwHi4VJYSKnYfirUqRfh5Gq2XwCq14fvKZTtBTRnrJ1K"

[programs.devnet]
nft = "CjLs3iFDVrtJwXpubVaGmz2hJrVR4F9UAYxma2oxwL2G"
solana_ft = "DwHi4VJYSKnYfirUqRfh5Gq2XwCq14fvKZTtBTRnrJ1K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"
